version: 2

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:bionic"
    steps:
      - checkout
      - run:
          name: Update packages
          command: 'sudo apt-get update'
      - run:
          name: Install build-essential
          command: 'sudo apt-get install -y build-essential'
      - run:
          name: Install cmake
          command: |
             # https://askubuntu.com/a/1157132
             sudo apt-get install software-properties-common
             sudo apt purge --auto-remove cmake
             wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
             sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
             sudo apt-get update
             sudo apt-get install cmake
             cmake --version
      - run:
          name: Install curl
          command: 'sudo apt-get install -y curl'
      - run:
          name: Install unzip
          command: 'sudo apt-get install -y unzip'
      - run:
          name: Build akumuli
          command: sudo ./all.sh
      - store_artifacts:
          path: akumuli.tar.gz
          destination: akumuli.tar.gz
      - store_artifacts:
          path: akumuli-library.tar.gz
          destination: akumuli-library.tar.gz
