version: 2

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:bionic"
    steps:
      - checkout
      - run:
          name: Update packages
          command: 'sudo apt-get update'
      - run:
          name: Install build-essential
          command: 'sudo apt-get install -y build-essential'
      - run:
          name: Install cmake
          command: 'sudo apt-get install -y cmake'
      - run:
          name: Install curl
          command: 'sudo apt-get install -y curl'
      - run:
          name: Install unzip
          command: 'sudo apt-get install -y unzip'
      - run:
          name: Build akumuli
          command: sudo ./all.sh
      - store_artifacts:
          path: akumuli.tar.gz
          destination: akumuli.tar.gz
      - store_artifacts:
          path: akumuli-library.tar.gz
          destination: akumuli-library.tar.gz
