name: akumuli-static

on: [push]

jobs:
  akumuli-static:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: install nodejs 12
      run: |
         sudo apt-get update
         sudo apt-get install -y build-essential
         sudo apt-get install -y cmake
         sudo apt-get install -y curl
         sudo apt-get install -y unzip
