name: akumuli-static

on: [push]

jobs:
  akumuli-static:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: install build essentials
      run: |
         sudo apt-get update
         sudo apt-get install -y build-essential
         sudo apt-get install -y cmake
         sudo apt-get install -y curl
         sudo apt-get install -y unzip

    - name: build
      run: |
         sudo mkdir -p /usr/local/share/akumuli-static
         sudo cp -rp *.* /usr/local/share/akumuli-static
         cd /usr/local/share/akumuli-static
         sudo ./all.sh
